#!/bin/bash
without_suffix=`echo $1|cut -d . -f1`
echo ""
#echo "************ Github Dork Links (must be logged in) *******************"
#echo "  tumblr.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22tumblr.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22tumblr.com%22&s=indexed&type=Code"
#echo "  medium.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22medium.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22medium.com%22&s=indexed&type=Code"
#echo "  reddit.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22reddit.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22reddit.com%22&s=indexed&type=Code"
#echo " firebaseio.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22firebaseio.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22firebaseio.com%22&s=indexed&type=Code"
#echo "  pinterest.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22pinterest.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22pinterest.com%22&s=indexed&type=Code"
#echo " youtube.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22youtube.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22youtube.com%22&s=indexed&type=Code"
#echo " github.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22github.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22github.com%22&s=indexed&type=Code"
#echo " vimeo.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22vimeo.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22vimeo.com%22&s=indexed&type=Code"
#echo "  storage.googleapis.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22storage.googleapis.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22storage.googleapis.com%22&s=indexed&type=Code"
#echo " flickr.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22flickr.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22flickr.com%22&s=indexed&type=Code"
#echo " npmjs.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22npmjs.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22npmjs.com%22&s=indexed&type=Code"
#echo "  facebook.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22facebook.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22facebook.com%22&s=indexed&type=Code"
#echo " instagram.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22instagram.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22instagram.com%22&s=indexed&type=Code"
#echo " linkedin.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22linkedin.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22linkedin.com%22&s=indexed&type=Code"
#echo "  twitter.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22twitter.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22twitter.com%22&s=indexed&type=Code"
#echo " s3.amazonaws.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22s3.amazonaws.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22s3.amazonaws.com%22&s=indexed&type=Code"
#echo " groups.google.com"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22groups.google.com%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22groups.google.com%22&s=indexed&type=Code"
#echo " telegram.me"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22telegram.me%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22telegram.me%22&s=indexed&type=Code"
#echo "  twitch.tv"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22twitch.tv%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22twitch.tv%22&s=indexed&type=Code"
#echo " bitbucket.org"
#echo "https://github.com/search?o=desc&q=org%3A$1+%22bitbucket.org%22&s=indexed&type=Code"
echo "https://github.com/search?o=desc&q=org%3A$without_suffix+%22bitbucket.org%22&s=indexed&type=Code"
